version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: mysecretpassword

  nextcloud:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
    environment:
      NEXTCLOUD_DB_TYPE: pgsql
      NEXTCLOUD_DB_HOST: db
      NEXTCLOUD_DB_PORT: 5432
      NEXTCLOUD_DB_NAME: nextcloud
      NEXTCLOUD_DB_USER: nextcloud
      NEXTCLOUD_DB_PASSWORD: mysecretpassword

  collabora:
    image: collabora/code
    container_name: collabora
    restart: always
    ports:
      - "9980:9980"
    cap_add:
      - MKNOD
    environment:
      - domain=34.70.191.205
      - username=admin
      - password=yourpassword
    networks:
      - internal_network

volumes:
  nextcloud_data:
    driver: local

networks:
  internal_network:
    driver: bridge

