version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: mysecretpassword
      
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile.nextcloud
    container_name: collabora
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
    environment:
      NEXTCLOUD_DB_TYPE: pgsql
      NEXTCLOUD_DB_HOST: db
      NEXTCLOUD_DB_PORT: 5432
      NEXTCLOUD_DB_NAME: nextcloud
      NEXTCLOUD_DB_USER: nextcloud
      NEXTCLOUD_DB_PASSWORD: NextcloudDBPasswordYobi

  collabora:
    build:
      context: .
      dockerfile: Dockerfile.nextcloud
    container_name: collabora
    restart: always
    ports:
      - "9980:9980"
    cap_add:
      - MKNOD
    environment:
      - domain=nc-media.yib.io
      - username=admin
      - password=NextcloudPasswordYobi
    networks:
      - internal_network

volumes:
  nextcloud_data:
    driver: local

networks:
  internal_network:
    driver: bridge

